import { useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useSearchParams } from 'react-router-dom'

import { Icon } from '../../../components/ui/Icon'
import { Badge, Button, ErrorState, Skeleton } from '../../../components/ui/Primitives'
import { cancelCopilotAction, confirmCopilotAction, copilotKeys, createConversation, getConversation, listConversations, sendCopilotMessage, type CopilotAction, type SendMessageInput } from '../api'

const suggestions = ['What should I post this week?', 'Analyze my best posts.', 'What topics perform best for me?', 'Create a draft based on my recent content.']

export function CopilotPage() {
  const client = useQueryClient(); const [params, setParams] = useSearchParams(); const selectedId = params.get('conversation') ?? ''
  const [content, setContent] = useState(''); const [useStyle, setUseStyle] = useState(true); const [useAnalytics, setUseAnalytics] = useState(true); const [useKnowledge, setUseKnowledge] = useState(false)
  const conversations = useQuery({ queryKey: copilotKeys.conversations, queryFn: listConversations })
  const conversation = useQuery({ queryKey: copilotKeys.conversation(selectedId), queryFn: () => getConversation(selectedId), enabled: Boolean(selectedId) })
  const send = useMutation({ mutationFn: async (input: SendMessageInput) => { let id = selectedId; if (!id) { const created = await createConversation(); id = created.id; setParams({ conversation: id }, { replace: true }) } return sendCopilotMessage(id, input) }, onSuccess: async (data) => { setContent(''); client.setQueryData(copilotKeys.conversation(data.conversation.id), data.conversation); await client.invalidateQueries({ queryKey: copilotKeys.conversations }) } })
  const action = useMutation({ mutationFn: ({ id, intent }: { id: string; intent: 'confirm' | 'cancel' }) => intent === 'confirm' ? confirmCopilotAction(id) : cancelCopilotAction(id), onSuccess: async () => { if (selectedId) await client.invalidateQueries({ queryKey: copilotKeys.conversation(selectedId) }) } })
  const submit = (event: FormEvent) => { event.preventDefault(); if (content.trim()) send.mutate({ content: content.trim(), use_writing_style: useStyle, use_analytics: useAnalytics, use_knowledge: useKnowledge }) }
  const choose = (id: string) => setParams({ conversation: id })
  return <div className="mx-auto grid max-w-[1240px] gap-5 lg:grid-cols-[250px_1fr]">
    <aside className="order-2 lg:order-1"><div className="mb-3 flex items-center justify-between"><p className="text-[10px] font-extrabold uppercase tracking-[0.14em] text-[#958da1]">Conversations</p><button aria-label="New conversation" className="grid size-8 place-items-center rounded-lg bg-[#eeeaff] text-[#6647eb]" onClick={() => setParams({})} type="button"><Icon className="size-4" name="plus"/></button></div>{conversations.isLoading ? <Skeleton className="h-48"/> : <div className="flex gap-2 overflow-x-auto lg:block lg:space-y-1">{conversations.data?.items.map((item) => <button className={`min-w-52 rounded-xl px-3 py-3 text-left lg:w-full ${selectedId === item.id ? 'bg-[#eeeaff] text-[#5f42e8]' : 'bg-white text-[#5f586b] hover:bg-[#f5f2f8]'}`} key={item.id} onClick={() => choose(item.id)} type="button"><p className="truncate text-[11px] font-bold">{item.title}</p><p className="mt-1 text-[9px] opacity-60">{new Date(item.last_message_at ?? item.created_at).toLocaleDateString()}</p></button>)}</div>}</aside>
    <section className="order-1 flex min-h-[calc(100vh-128px)] flex-col overflow-hidden rounded-[20px] border border-[#e8e3ee] bg-white shadow-[0_12px_40px_rgba(44,34,70,.06)] lg:order-2">
      <header className="border-b border-[#eeeaf2] px-5 py-4 sm:px-7"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-gradient-to-br from-[#7656ff] to-[#a767f5] text-white"><Icon name="sparkle"/></span><div><h1 className="text-base font-extrabold text-[#272237]">AI Copilot</h1><p className="text-[11px] text-[#81798d]">Ask about your authorized workspace content.</p></div><Badge tone="violet">Review-first</Badge></div></header>
      <div className="flex-1 overflow-y-auto px-4 py-6 sm:px-7">{conversation.isLoading ? <div className="space-y-4"><Skeleton className="h-24"/><Skeleton className="ml-auto h-16 w-3/4"/><Skeleton className="h-36 w-4/5"/></div> : conversation.isError ? <ErrorState message="This conversation could not be loaded." retry={() => void conversation.refetch()}/> : !conversation.data?.messages.length ? <Welcome onSelect={setContent}/> : <div className="space-y-5">{conversation.data.messages.map((message) => <Message actionPending={action.isPending} key={message.id} message={message} onAction={(id, intent) => action.mutate({ id, intent })}/>)}</div>}</div>
      <form className="border-t border-[#eeeaf2] bg-[#fbfafd] p-4 sm:p-5" onSubmit={submit}><div className="rounded-2xl border border-[#dfd9e8] bg-white p-3 shadow-sm focus-within:border-[#9d89f1] focus-within:ring-2 focus-within:ring-[#eeeaff]"><textarea aria-label="Ask AI" className="min-h-20 w-full resize-none bg-transparent text-[13px] leading-5 outline-none placeholder:text-[#aaa3b4]" disabled={send.isPending} onChange={(event) => setContent(event.target.value)} placeholder="Ask about your content, analytics, ideas, or next plan…" value={content}/><div className="mt-2 flex flex-wrap items-center gap-3 border-t border-[#f0edf3] pt-3"><ContextToggle checked={useStyle} label="Writing style" onChange={setUseStyle}/><ContextToggle checked={useAnalytics} label="Analytics" onChange={setUseAnalytics}/><ContextToggle checked={useKnowledge} label="My knowledge" onChange={setUseKnowledge}/><Button className="ml-auto" disabled={send.isPending || content.trim().length < 2} type="submit">{send.isPending ? 'Thinking…' : 'Ask AI'}<Icon className="size-3.5" name="arrow"/></Button></div></div>{send.isError && <div className="mt-3"><ErrorState message={send.error.message}/></div>}<p className="mt-2 text-center text-[9px] text-[#a19aa9]">AI can make mistakes. Review all content and confirm every change.</p></form>
    </section>
  </div>
}

function Welcome({ onSelect }: { onSelect: (value: string) => void }) { return <div className="mx-auto max-w-2xl py-8 text-center"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-[#eeeaff] text-[#694aec]"><Icon className="size-6" name="sparkle"/></span><h2 className="mt-4 text-xl font-extrabold tracking-[-0.03em]">What can I help you create?</h2><p className="mx-auto mt-2 max-w-lg text-xs leading-5 text-[#7d7588]">I can analyze your authorized content and suggest next steps. Private knowledge is used only when you enable it.</p><div className="mt-6 grid gap-2 sm:grid-cols-2">{suggestions.map((text) => <button className="rounded-xl border border-[#e6e1ec] bg-[#fbfafd] px-4 py-3 text-left text-[11px] font-semibold text-[#554e61] hover:border-[#bfb2ec] hover:bg-[#f5f1ff]" key={text} onClick={() => onSelect(text)} type="button">{text}</button>)}</div></div> }

function Message({ message, onAction, actionPending }: { message: import('../api').CopilotMessage; onAction: (id: string, intent: 'confirm' | 'cancel') => void; actionPending: boolean }) { const assistant = message.role === 'assistant'; return <div className={`flex ${assistant ? 'justify-start' : 'justify-end'}`}><div className={`max-w-[88%] rounded-2xl px-4 py-3 sm:max-w-[78%] ${assistant ? 'border border-[#ebe6f0] bg-[#fcfbfd]' : 'bg-[#312b43] text-white'}`}><p className="whitespace-pre-line text-[12px] leading-5">{message.content}</p>{assistant && message.evidence.length > 0 && <div className="mt-3 space-y-1.5 border-t border-[#ebe7ef] pt-3"><p className="text-[9px] font-extrabold uppercase tracking-wide text-[#8174ba]">Evidence</p>{message.evidence.map((item, index) => <div className="rounded-lg bg-white px-3 py-2 text-[10px]" key={`${item.label}-${index}`}><span className="font-bold text-[#423a50]">{item.label}: </span><span className="text-[#746d7e]">{item.value}</span>{item.post_id && <Link className="ml-2 font-bold text-[#6849ed]" to={`/posts/${item.post_id}`}>View post</Link>}</div>)}</div>}{assistant && message.suggested_action && <p className="mt-3 text-[10px] font-semibold text-[#665d72]">Suggested: {message.suggested_action}</p>}{message.action && <ActionCard action={message.action} disabled={actionPending} onAction={onAction}/>}</div></div> }

function ActionCard({ action, onAction, disabled }: { action: CopilotAction; onAction: (id: string, intent: 'confirm' | 'cancel') => void; disabled: boolean }) { const title = typeof action.arguments.title === 'string' ? action.arguments.title : 'Untitled draft'; return <div className="mt-3 rounded-xl border border-[#dcd3fa] bg-[#f5f2ff] p-3"><div className="flex items-center justify-between gap-2"><p className="text-[10px] font-extrabold uppercase tracking-wide text-[#6548dc]">Proposed draft</p><Badge tone={action.status === 'EXECUTED' ? 'green' : action.status === 'PENDING' ? 'amber' : 'neutral'}>{action.status}</Badge></div><p className="mt-2 text-xs font-bold text-[#3e3650]">{title}</p>{action.status === 'PENDING' && <div className="mt-3 flex gap-2"><Button disabled={disabled} onClick={() => onAction(action.id, 'confirm')}>Create draft</Button><Button disabled={disabled} onClick={() => onAction(action.id, 'cancel')} variant="secondary">Cancel</Button></div>}{action.status === 'EXECUTED' && action.result && !Array.isArray(action.result) && typeof action.result.id === 'string' && <Link className="mt-3 inline-block text-[11px] font-bold text-[#6447e3]" to={`/posts/${action.result.id}`}>Open created draft →</Link>}</div> }

function ContextToggle({ checked, label, onChange }: { checked: boolean; label: string; onChange: (value: boolean) => void }) { return <label className="flex items-center gap-1.5 text-[9px] font-bold text-[#716a7b]"><input checked={checked} onChange={(event) => onChange(event.target.checked)} type="checkbox"/>{label}</label> }
