import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'

import { Badge, Button, Card, ErrorState, Skeleton } from '../../../components/ui/Primitives'
import { activateWorkspace, createWorkspace, listWorkspaces, workspaceKeys } from '../api'

export function WorkspaceSettingsCard() {
  const client = useQueryClient(); const [open, setOpen] = useState(false); const [name, setName] = useState(''); const [kind, setKind] = useState('client')
  const workspaces = useQuery({ queryKey: workspaceKeys.all, queryFn: listWorkspaces })
  const create = useMutation({ mutationFn: () => createWorkspace(name, kind), onSuccess: async () => { await client.invalidateQueries({ queryKey: workspaceKeys.all }); setOpen(false); setName('') } })
  const activate = useMutation({ mutationFn: activateWorkspace, onSuccess: async () => { await client.invalidateQueries(); window.location.reload() } })
  return <Card className="p-5 lg:col-span-2"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Workspaces</p><h2 className="mt-2 text-base font-bold">LinkedIn identities</h2><p className="mt-1 text-[13px] text-slate-500">Each workspace has a separate LinkedIn OAuth connection. Every identity still requires its own authorized consent.</p></div><Button onClick={() => setOpen(!open)} variant="secondary">{open ? 'Cancel' : 'Create workspace'}</Button></div>{open && <div className="mt-4 grid gap-3 rounded-xl bg-slate-50 p-4 sm:grid-cols-[1fr_160px_auto]"><input className="app-input" maxLength={120} placeholder="Workspace name" value={name} onChange={(event) => setName(event.target.value)}/><select className="app-input" value={kind} onChange={(event) => setKind(event.target.value)}><option value="personal">Personal</option><option value="company">Company</option><option value="client">Client</option></select><Button disabled={create.isPending || !name.trim()} onClick={() => create.mutate()}>{create.isPending ? 'Creating...' : 'Create'}</Button></div>}{create.isError && <div className="mt-4"><ErrorState message={create.error.message}/></div>}{workspaces.isLoading ? <Skeleton className="mt-4 h-20"/> : <div className="mt-4 grid gap-3 sm:grid-cols-2">{workspaces.data?.items.map((workspace) => <div className={`rounded-xl border p-4 ${workspace.is_current ? 'border-indigo-200 bg-indigo-50/50' : 'border-slate-200'}`} key={workspace.id}><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><p className="text-sm font-bold">{workspace.name}</p>{workspace.is_default && <Badge tone="neutral">Default</Badge>}</div><p className="mt-1 text-[10px] capitalize text-slate-400">{workspace.kind}</p></div>{workspace.is_current ? <Badge tone="green">Current</Badge> : <Button disabled={activate.isPending} onClick={() => activate.mutate(workspace.id)} variant="ghost">Switch</Button>}</div></div>)}</div>}</Card>
}
