import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link } from 'react-router-dom'

import { Badge, Button, Card, EmptyState, ErrorState, PageHeader, Skeleton } from '../../../components/ui/Primitives'
import {
  approvePlan, createPostFromIdea, generateIdeas, generatePlan, listIdeas, listPlans,
  repurposeContent, saveIdea, studioKeys, type ContentPlan, type GeneratedIdea,
} from '../api'

type Tab = 'ideas' | 'repurpose' | 'planner'
const field = 'mt-1.5 h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm outline-none focus:border-indigo-400'
const label = 'text-[11px] font-bold uppercase tracking-wide text-slate-500'

export function ContentStudioPage() {
  const [tab, setTab] = useState<Tab>('ideas')
  return <div className="mx-auto max-w-[1180px]">
    <PageHeader eyebrow="AI Content Studio" title="Ideas, repurposing and planning" description="Turn a topic or source into an organized LinkedIn content pipeline." />
    <div className="mb-5 flex gap-1 rounded-xl border border-slate-200 bg-white p-1.5">
      {([['ideas', 'Content Ideas'], ['repurpose', 'Repurpose'], ['planner', 'Content Planner']] as const).map(([value, text]) => <button className={`flex-1 rounded-lg px-3 py-2 text-xs font-bold transition ${tab === value ? 'bg-[#4f5ff7] text-white shadow-sm' : 'text-slate-500 hover:bg-slate-50'}`} key={value} onClick={() => setTab(value)} type="button">{text}</button>)}
    </div>
    {tab === 'ideas' && <IdeasPanel/>}
    {tab === 'repurpose' && <RepurposePanel/>}
    {tab === 'planner' && <PlannerPanel/>}
  </div>
}

function IdeasPanel() {
  const client = useQueryClient(); const [topics, setTopics] = useState('AI agents'); const [audience, setAudience] = useState('Developers'); const [count, setCount] = useState(5); const [generated, setGenerated] = useState<GeneratedIdea[]>([])
  const saved = useQuery({ queryKey: studioKeys.ideas, queryFn: listIdeas })
  const generate = useMutation({ mutationFn: generateIdeas, onSuccess: (data) => setGenerated(data.ideas) })
  const save = useMutation({ mutationFn: saveIdea, onSuccess: () => void client.invalidateQueries({ queryKey: studioKeys.ideas }) })
  const create = useMutation({ mutationFn: createPostFromIdea, onSuccess: () => void client.invalidateQueries({ queryKey: studioKeys.ideas }) })
  return <div className="grid gap-5 lg:grid-cols-[330px_1fr]">
    <Card className="h-fit p-5"><h2 className="text-sm font-bold">Generate fresh ideas</h2><p className="mt-1 text-xs leading-5 text-slate-500">Use commas to combine related themes.</p><div className="mt-5 space-y-4"><label className={label}>Topics<input className={field} value={topics} onChange={(event) => setTopics(event.target.value)}/></label><label className={label}>Audience<input className={field} value={audience} onChange={(event) => setAudience(event.target.value)}/></label><label className={label}>Number of ideas<select className={field} value={count} onChange={(event) => setCount(Number(event.target.value))}>{[3, 5, 10].map((item) => <option key={item}>{item}</option>)}</select></label><Button className="w-full" disabled={generate.isPending} onClick={() => generate.mutate({ topics: topics.split(',').map((item) => item.trim()).filter(Boolean), audience, count })}>{generate.isPending ? '✨ Creating ideas...' : 'Generate ideas'}</Button>{generate.isError && <ErrorState message={generate.error.message}/>}</div></Card>
    <div className="space-y-5">{generated.length > 0 && <IdeaList ideas={generated} onSave={(idea) => save.mutate(idea)} saving={save.isPending}/>}<Card className="p-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-sm font-bold">Saved ideas</h2><Badge tone="violet">{saved.data?.total ?? 0}</Badge></div>{saved.isLoading ? <Skeleton className="h-40"/> : saved.isError ? <ErrorState message={saved.error.message}/> : !saved.data?.items.length ? <EmptyState title="No saved ideas yet" description="Generate ideas above, then save the ones worth developing."/> : <div className="space-y-3">{saved.data.items.map((idea) => <article className="rounded-xl border border-slate-200 p-4" key={idea.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><Badge tone={idea.status === 'USED' ? 'green' : 'blue'}>{idea.category}</Badge><h3 className="mt-2 text-sm font-bold">{idea.title}</h3><p className="mt-1 text-xs text-slate-500">{idea.description}</p></div>{idea.status === 'NEW' && <Button disabled={create.isPending} onClick={() => create.mutate(idea.id)} variant="secondary">Create draft</Button>}</div></article>)}</div>}</Card></div>
  </div>
}

function IdeaList({ ideas, onSave, saving }: { ideas: GeneratedIdea[]; onSave: (idea: GeneratedIdea) => void; saving: boolean }) {
  return <Card className="p-5"><h2 className="mb-4 text-sm font-bold">Generated ideas</h2><div className="grid gap-3 md:grid-cols-2">{ideas.map((idea, index) => <article className="rounded-xl border border-slate-200 p-4" key={`${idea.title}-${index}`}><div className="flex items-center justify-between gap-2"><Badge tone="violet">{idea.category}</Badge><span className="text-[10px] font-semibold text-slate-400">{idea.suggested_format}</span></div><h3 className="mt-3 text-sm font-bold">{idea.title}</h3><p className="mt-1.5 text-xs leading-5 text-slate-500">{idea.description}</p><p className="mt-3 rounded-lg bg-slate-50 p-3 text-xs font-medium text-slate-700">“{idea.suggested_hook}”</p><Button className="mt-3" disabled={saving} onClick={() => onSave(idea)} variant="secondary">Save idea</Button></article>)}</div></Card>
}

function RepurposePanel() {
  const [source, setSource] = useState(''); const [sourceType, setSourceType] = useState('paste_text'); const [format, setFormat] = useState('linkedin_post'); const [count, setCount] = useState(3)
  const mutation = useMutation({ mutationFn: repurposeContent })
  return <div className="grid gap-5 lg:grid-cols-[1fr_1fr]"><Card className="p-5"><h2 className="text-sm font-bold">Transform existing content</h2><p className="mt-1 text-xs text-slate-500">The source is treated as reference material and will never be followed as instructions.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className={label}>Source type<select className={field} value={sourceType} onChange={(event) => setSourceType(event.target.value)}><option value="paste_text">Pasted text</option><option value="blog_article">Blog article</option><option value="linkedin_post">LinkedIn post</option><option value="notes">Notes</option><option value="url">Extracted URL content</option></select></label><label className={label}>Output<select className={field} value={format} onChange={(event) => setFormat(event.target.value)}><option value="linkedin_post">LinkedIn posts</option><option value="linkedin_carousel">Carousel outlines</option><option value="linkedin_short_post">Short posts</option><option value="linkedin_long_form">Long-form posts</option><option value="x_thread">X thread</option><option value="newsletter">Newsletter</option><option value="video_script">Video script</option></select></label><label className={`${label} sm:col-span-2`}>Source content<textarea className="mt-1.5 min-h-56 w-full rounded-lg border border-slate-200 p-3 text-sm outline-none focus:border-indigo-400" placeholder="Paste at least 30 characters of source material..." value={source} onChange={(event) => setSource(event.target.value)}/></label><label className={label}>Variations<select className={field} value={count} onChange={(event) => setCount(Number(event.target.value))}>{[1, 3, 5, 10].map((item) => <option key={item}>{item}</option>)}</select></label></div><Button className="mt-5 w-full" disabled={mutation.isPending || source.trim().length < 30} onClick={() => mutation.mutate({ source_type: sourceType, source_content: source, output_format: format, count, tone: 'Conversational' })}>{mutation.isPending ? '✨ Repurposing content...' : 'Create draft series'}</Button>{mutation.isError && <div className="mt-4"><ErrorState message={mutation.error.message}/></div>}</Card><Card className="p-5"><h2 className="mb-4 text-sm font-bold">Generated drafts</h2>{!mutation.data ? <EmptyState title="Your drafts will appear here" description="Each result is saved as a draft for your review—nothing is published automatically."/> : <div className="space-y-3">{mutation.data.posts.map((post) => <article className="rounded-xl border border-slate-200 p-4" key={post.id}><h3 className="text-sm font-bold">{post.title}</h3><p className="mt-2 line-clamp-4 whitespace-pre-line text-xs leading-5 text-slate-500">{post.content}</p><Link className="mt-3 inline-block text-xs font-bold text-indigo-600" to={`/posts/${post.id}`}>Open editor →</Link></article>)}</div>}</Card></div>
}

function PlannerPanel() {
  const client = useQueryClient(); const today = new Date().toISOString().slice(0, 10); const [form, setForm] = useState({ name: 'My content plan', frequency: '3_per_week', duration_days: 7, topics: 'AI, software engineering', audience: 'Developers', start_date: today, posting_time: '10:00', timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC' }); const [autoPublish, setAutoPublish] = useState(false)
  const plans = useQuery({ queryKey: studioKeys.plans, queryFn: listPlans })
  const generate = useMutation({ mutationFn: generatePlan, onSuccess: () => void client.invalidateQueries({ queryKey: studioKeys.plans }) })
  const approve = useMutation({ mutationFn: ({ id }: { id: string }) => approvePlan(id, autoPublish), onSuccess: () => void client.invalidateQueries({ queryKey: studioKeys.plans }) })
  const update = (name: string, value: string | number) => setForm((current) => ({ ...current, [name]: value }))
  return <div className="grid gap-5 lg:grid-cols-[360px_1fr]"><Card className="h-fit p-5"><h2 className="text-sm font-bold">Build a content plan</h2><div className="mt-5 space-y-4"><label className={label}>Plan name<input className={field} value={form.name} onChange={(event) => update('name', event.target.value)}/></label><label className={label}>Topics<input className={field} value={form.topics} onChange={(event) => update('topics', event.target.value)}/></label><label className={label}>Audience<input className={field} value={form.audience} onChange={(event) => update('audience', event.target.value)}/></label><div className="grid grid-cols-2 gap-3"><label className={label}>Frequency<select className={field} value={form.frequency} onChange={(event) => update('frequency', event.target.value)}><option value="2_per_week">2 / week</option><option value="3_per_week">3 / week</option><option value="5_per_week">5 / week</option><option value="daily">Daily</option></select></label><label className={label}>Duration<select className={field} value={form.duration_days} onChange={(event) => update('duration_days', Number(event.target.value))}><option value={7}>1 week</option><option value={14}>2 weeks</option><option value={30}>1 month</option></select></label><label className={label}>Start date<input className={field} min={today} type="date" value={form.start_date} onChange={(event) => update('start_date', event.target.value)}/></label><label className={label}>Time<input className={field} type="time" value={form.posting_time} onChange={(event) => update('posting_time', event.target.value)}/></label></div><Button className="w-full" disabled={generate.isPending} onClick={() => generate.mutate({ ...form, topics: form.topics.split(',').map((item) => item.trim()).filter(Boolean) })}>{generate.isPending ? '✨ Planning content...' : 'Generate plan'}</Button>{generate.isError && <ErrorState message={generate.error.message}/>}</div></Card><div>{plans.isLoading ? <Skeleton className="h-80"/> : plans.isError ? <ErrorState message={plans.error.message}/> : !plans.data?.items.length ? <EmptyState title="No content plans yet" description="Choose a cadence and topics to create your first plan."/> : <div className="space-y-4">{plans.data.items.map((plan) => <PlanCard autoPublish={autoPublish} approving={approve.isPending} key={plan.id} onApprove={() => approve.mutate({ id: plan.id })} onAutoPublish={setAutoPublish} plan={plan}/>)}</div>}</div></div>
}

function PlanCard({ plan, autoPublish, onAutoPublish, onApprove, approving }: { plan: ContentPlan; autoPublish: boolean; onAutoPublish: (value: boolean) => void; onApprove: () => void; approving: boolean }) {
  return <Card className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h2 className="text-sm font-bold">{plan.name}</h2><Badge tone={plan.status === 'APPROVED' ? 'green' : 'amber'}>{plan.status}</Badge></div><p className="mt-1 text-xs text-slate-500">{plan.items.length} posts · {plan.audience} · {plan.timezone}</p></div>{plan.status === 'DRAFT' && <Button disabled={approving} onClick={onApprove}>{approving ? 'Approving...' : 'Approve plan'}</Button>}</div><div className="mt-4 space-y-2">{plan.items.map((item) => <div className="flex gap-3 rounded-lg border border-slate-100 bg-slate-50/70 p-3" key={item.id}><time className="w-24 shrink-0 text-[10px] font-bold uppercase text-indigo-600">{new Date(item.scheduled_for).toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' })}</time><div><p className="text-xs font-bold">{item.title}</p><p className="mt-0.5 text-[11px] text-slate-500">{item.post_type} · {item.topic}</p></div></div>)}</div>{plan.status === 'DRAFT' && <label className="mt-4 flex items-start gap-2 rounded-lg border border-amber-100 bg-amber-50 p-3 text-xs text-amber-900"><input checked={autoPublish} className="mt-0.5" onChange={(event) => onAutoPublish(event.target.checked)} type="checkbox"/><span><strong>Schedule automatic publishing</strong><br/>Off by default. When enabled, approving creates active schedules for these dates.</span></label>}</Card>
}
