import { useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'

import { Badge, Button, Card, EmptyState, ErrorState, PageHeader, Skeleton } from '../../../components/ui/Primitives'
import { createKnowledge, deleteKnowledge, knowledgeKeys, listKnowledge, type KnowledgeCategory } from '../api'

const categories: [KnowledgeCategory, string][] = [['project', 'Project'], ['resume', 'Resume'], ['skill', 'Skill'], ['experience', 'Experience'], ['article', 'Article'], ['note', 'Note'], ['previous_content', 'Previous content'], ['achievement', 'Achievement'], ['technical_knowledge', 'Technical knowledge']]

export function KnowledgePage() {
  const client = useQueryClient(); const [open, setOpen] = useState(false); const [category, setCategory] = useState<KnowledgeCategory>('project'); const [title, setTitle] = useState(''); const [content, setContent] = useState(''); const [tags, setTags] = useState('')
  const items = useQuery({ queryKey: knowledgeKeys.all, queryFn: listKnowledge })
  const create = useMutation({ mutationFn: createKnowledge, onSuccess: async () => { await client.invalidateQueries({ queryKey: knowledgeKeys.all }); setOpen(false); setTitle(''); setContent(''); setTags('') } })
  const remove = useMutation({ mutationFn: deleteKnowledge, onSuccess: () => client.invalidateQueries({ queryKey: knowledgeKeys.all }) })
  const submit = (event: FormEvent) => { event.preventDefault(); create.mutate({ category, title, content, tags: tags.split(',').map((tag) => tag.trim()).filter(Boolean), is_private: true }) }
  return <div className="mx-auto max-w-[1120px]"><PageHeader eyebrow="Personal context" title="My knowledge" description="Store private context and choose exactly what AI may use in each generation." action={<Button onClick={() => setOpen((value) => !value)}>{open ? 'Close' : 'Add knowledge'}</Button>}/>{open && <Card className="mb-5 p-5"><form className="grid gap-4 md:grid-cols-2" onSubmit={submit}><label className="text-xs font-bold text-slate-600">Category<select className="app-input mt-1.5" value={category} onChange={(event) => setCategory(event.target.value as KnowledgeCategory)}>{categories.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select></label><label className="text-xs font-bold text-slate-600">Title<input className="app-input mt-1.5" maxLength={240} required value={title} onChange={(event) => setTitle(event.target.value)}/></label><label className="text-xs font-bold text-slate-600 md:col-span-2">Details<textarea className="app-input mt-1.5 min-h-32" maxLength={10000} required value={content} onChange={(event) => setContent(event.target.value)}/></label><label className="text-xs font-bold text-slate-600 md:col-span-2">Tags<input className="app-input mt-1.5" placeholder="React, Python, project" value={tags} onChange={(event) => setTags(event.target.value)}/></label><p className="text-xs text-slate-500">Private by default. Saving does not automatically include this in AI prompts.</p><div className="flex justify-end"><Button disabled={create.isPending} type="submit">{create.isPending ? 'Saving...' : 'Save knowledge'}</Button></div>{create.isError && <div className="md:col-span-2"><ErrorState message={create.error.message}/></div>}</form></Card>}{items.isLoading ? <div className="grid gap-4 md:grid-cols-2"><Skeleton className="h-44"/><Skeleton className="h-44"/></div> : items.isError ? <ErrorState message={items.error.message}/> : !items.data?.items.length ? <EmptyState title="Your knowledge base is empty" description="Add projects, skills, experience, or notes to personalize future content."/> : <div className="grid gap-4 md:grid-cols-2">{items.data.items.map((item) => <Card className="p-5" key={item.id}><div className="flex items-start justify-between gap-3"><div><Badge tone="violet">{item.category.replace('_', ' ')}</Badge><h2 className="mt-2 text-sm font-bold">{item.title}</h2></div><Button disabled={remove.isPending} onClick={() => remove.mutate(item.id)} variant="ghost">Delete</Button></div><p className="mt-3 line-clamp-5 whitespace-pre-line text-xs leading-5 text-slate-600">{item.content}</p>{item.tags.length > 0 && <div className="mt-4 flex flex-wrap gap-1.5">{item.tags.map((tag) => <span className="rounded-md bg-slate-100 px-2 py-1 text-[10px] font-semibold text-slate-500" key={tag}>{tag}</span>)}</div>}</Card>)}</div>}</div>
}
