import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'

import { Badge, Button, Card, ErrorState, Skeleton } from '../../../components/ui/Primitives'
import { creatorProgressKeys, getCreatorProgress, updateCreatorGoal } from '../api'

export function CreatorProgressCard() {
  const client = useQueryClient(); const progress = useQuery({ queryKey: creatorProgressKeys.all, queryFn: getCreatorProgress }); const [editing, setEditing] = useState(false); const [target, setTarget] = useState(8)
  const update = useMutation({ mutationFn: updateCreatorGoal, onSuccess: async () => { await client.invalidateQueries({ queryKey: creatorProgressKeys.all }); setEditing(false) } })
  if (progress.isLoading) return <Skeleton className="h-64"/>
  if (progress.isError || !progress.data) return <ErrorState message="Creator progress could not be loaded." retry={() => void progress.refetch()}/>
  const data = progress.data; const levelPercent = Math.round(data.level_points / data.next_level_points * 100)
  return <Card className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-indigo-500">Creator progress</p><h2 className="mt-1 text-lg font-bold">Level {data.creator_level}</h2></div><div className="text-right"><p className="text-xl font-bold text-orange-500">🔥 {data.current_streak}</p><p className="text-[9px] font-semibold text-slate-400">day publishing streak</p></div></div><div className="mt-4"><div className="mb-1.5 flex justify-between text-[10px] font-semibold text-slate-500"><span>Level progress</span><span>{data.level_points}/{data.next_level_points}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-500" style={{ width: `${levelPercent}%` }}/></div></div><div className="mt-4 rounded-xl bg-slate-50 p-4"><div className="flex items-center justify-between"><div><p className="text-xs font-bold">Monthly publishing goal</p><p className="mt-1 text-[10px] text-slate-500">{data.monthly_posts_published} of {data.monthly_post_target} posts</p></div><button className="text-[10px] font-bold text-indigo-600" onClick={() => { setTarget(data.monthly_post_target); setEditing(!editing) }} type="button">Edit goal</button></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${data.monthly_goal_percent}%` }}/></div>{editing && <div className="mt-3 flex gap-2"><input className="app-input h-9" max={100} min={1} type="number" value={target} onChange={(event) => setTarget(Number(event.target.value))}/><Button disabled={update.isPending} onClick={() => update.mutate(target)}>Save</Button></div>}</div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><Metric label="Published" value={data.posts_published}/><Metric label="Drafts" value={data.drafts_created}/><Metric label="Idea runs" value={data.ideas_generated}/></div>{data.achievements.length > 0 && <div className="mt-5 border-t border-slate-100 pt-4"><p className="mb-3 text-[10px] font-bold uppercase tracking-wide text-slate-400">Achievements</p><div className="flex flex-wrap gap-2">{data.achievements.slice(0, 4).map((item) => <span className="group relative" key={item.code}><Badge tone="amber">🏆 {item.title}</Badge><span className="pointer-events-none absolute bottom-full left-0 z-10 mb-2 hidden w-48 rounded-lg bg-slate-900 p-2 text-[10px] text-white group-hover:block">{item.description}</span></span>)}</div></div>}{data.total_impressions == null && <p className="mt-4 text-[9px] leading-4 text-slate-400">Impression achievements remain unavailable until LinkedIn provides analytics.</p>}</Card>
}

function Metric({ label, value }: { label: string; value: number }) { return <div><p className="text-base font-bold">{value}</p><p className="text-[9px] text-slate-400">{label}</p></div> }
