import { useDeferredValue, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link } from 'react-router-dom'

import { Icon } from '../../../components/ui/Icon'
import { Badge, Button, Card, EmptyState, ErrorState, PageHeader, Skeleton } from '../../../components/ui/Primitives'
import { campaignKeys, listCampaigns } from '../../campaigns/api'
import { deletePost, listPosts, postKeys, type PostStatus } from '../api'

const statusTone: Record<PostStatus, 'neutral' | 'blue' | 'green' | 'amber' | 'red'> = { DRAFT: 'amber', APPROVED: 'blue', SCHEDULED: 'blue', PUBLISHING: 'blue', PUBLISHED: 'green', FAILED: 'red', CANCELLED: 'neutral' }

export function PostsPage() {
  const [search, setSearch] = useState(''); const deferredSearch = useDeferredValue(search)
  const [status, setStatus] = useState<PostStatus | ''>(''); const [offset, setOffset] = useState(0); const limit = 10
  const queryClient = useQueryClient()
  const posts = useQuery({ queryKey: [...postKeys.all, deferredSearch, status, offset], queryFn: () => listPosts({ search: deferredSearch, status: status || undefined, offset, limit }) })
  const campaigns = useQuery({ queryKey: [...campaignKeys.all, 'post-labels'], queryFn: () => listCampaigns({ limit: 100 }) })
  const remove = useMutation({ mutationFn: deletePost, onSuccess: () => queryClient.invalidateQueries({ queryKey: postKeys.all }) })
  const campaignNames = new Map(campaigns.data?.items.map((campaign) => [campaign.id, campaign.name]))
  return <div className="mx-auto max-w-[1120px]"><PageHeader description="Search, review, and continue working on your posts." title="Content library" action={<Link className="inline-flex h-9 items-center gap-2 rounded-lg bg-[#4f5ff7] px-4 text-[12px] font-bold text-white" to="/create"><Icon className="size-4" name="plus"/>New post</Link>}/><Card className="overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row"><label className="relative flex-1"><span className="sr-only">Search posts</span><Icon className="absolute left-3 top-2.5 size-4 text-slate-400" name="search"/><input className="app-input pl-9" onChange={(event) => { setSearch(event.target.value); setOffset(0) }} placeholder="Search posts by title or content…" value={search}/></label><select aria-label="Filter by status" className="app-input sm:w-44" onChange={(event) => { setStatus(event.target.value as PostStatus | ''); setOffset(0) }} value={status}><option value="">All statuses</option>{['DRAFT','APPROVED','SCHEDULED','PUBLISHED','FAILED','CANCELLED'].map((value) => <option key={value} value={value}>{titleCase(value)}</option>)}</select></div>
    {posts.isLoading ? <div className="space-y-2 p-4">{Array.from({ length: 5 }, (_, index) => <Skeleton className="h-14" key={index}/>)}</div> : posts.isError ? <div className="p-4"><ErrorState message="Unable to load your posts." retry={() => void posts.refetch()}/></div> : !posts.data?.items.length ? <div className="p-4"><EmptyState action={<Link className="text-xs font-bold text-[#4f5ff7]" to="/create">Create a post</Link>} description="Adjust your filters or create your first draft." title="No posts found"/></div> : <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-slate-50/80 text-[9px] font-bold uppercase tracking-[0.1em] text-slate-400"><tr><th className="px-5 py-3">Post</th><th className="px-4 py-3">Campaign</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Updated</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody>{posts.data.items.map((post) => <tr className="border-t border-slate-100 text-[12px]" key={post.id}><td className="max-w-md px-5 py-3.5"><p className="truncate font-bold text-slate-800">{post.title || 'Untitled post'}</p><p className="mt-1 truncate text-[10px] text-slate-400">{post.content}</p></td><td className="px-4 py-3.5 text-slate-500">{post.campaign_id ? campaignNames.get(post.campaign_id) ?? 'Campaign' : '—'}</td><td className="px-4 py-3.5"><Badge tone={statusTone[post.status]}>{titleCase(post.status)}</Badge></td><td className="px-4 py-3.5 text-slate-500">{formatDate(post.updated_at)}</td><td className="px-5 py-3.5"><div className="flex justify-end gap-1">{post.status === 'DRAFT' && <Link aria-label={`Edit ${post.title ?? 'post'}`} className="rounded-md px-2.5 py-1.5 font-bold text-[#4f5ff7] hover:bg-indigo-50" to={`/posts/${post.id}`}>Edit</Link>}{post.status === 'DRAFT' && <button aria-label={`Delete ${post.title ?? 'post'}`} className="rounded-md p-1.5 text-slate-400 hover:bg-red-50 hover:text-red-600" onClick={() => window.confirm('Delete this draft?') && remove.mutate(post.id)} type="button"><Icon className="size-4" name="trash"/></button>}</div></td></tr>)}</tbody></table></div>}
    {posts.data && posts.data.total > limit && <div className="flex items-center justify-between border-t border-slate-100 px-5 py-3"><p className="text-[10px] text-slate-400">Showing {offset + 1}–{Math.min(offset + limit, posts.data.total)} of {posts.data.total}</p><div className="flex gap-2"><Button disabled={offset === 0} onClick={() => setOffset(Math.max(0, offset - limit))} variant="secondary">Previous</Button><Button disabled={offset + limit >= posts.data.total} onClick={() => setOffset(offset + limit)} variant="secondary">Next</Button></div></div>}
  </Card></div>
}
function titleCase(value: string) { return value.toLowerCase().replace(/(^|_)(\w)/g, (_, space: string, letter: string) => `${space ? ' ' : ''}${letter.toUpperCase()}`) }
function formatDate(value: string) { return new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(value)) }
