"""add authentication tokens

Revision ID: 27778c75d2b5
Revises: b12a1f75ad14
Create Date: 2026-09-27 01:22:25.112418
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '27778c75d2b5'
down_revision: str | None = 'b12a1f75ad14'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('REFRESH', 'EMAIL_VERIFICATION', 'PASSWORD_RESET', name='authtokenkind', native_enum=False, length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['auth_tokens.id'], name=op.f('fk_auth_tokens_replaced_by_id_auth_tokens'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auth_tokens_token_hash'))
    )
    op.create_index(op.f('ix_auth_tokens_expires_at'), 'auth_tokens', ['expires_at'], unique=False)
    op.create_index('ix_auth_tokens_family', 'auth_tokens', ['family_id', 'revoked_at'], unique=False)
    op.create_index(op.f('ix_auth_tokens_family_id'), 'auth_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_auth_tokens_kind'), 'auth_tokens', ['kind'], unique=False)
    op.create_index(op.f('ix_auth_tokens_user_id'), 'auth_tokens', ['user_id'], unique=False)
    op.create_index('ix_auth_tokens_user_kind', 'auth_tokens', ['user_id', 'kind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auth_tokens_user_kind', table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_user_id'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_kind'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_family_id'), table_name='auth_tokens')
    op.drop_index('ix_auth_tokens_family', table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_expires_at'), table_name='auth_tokens')
    op.drop_table('auth_tokens')
    # ### end Alembic commands ###

