import type { ButtonHTMLAttributes, PropsWithChildren, ReactNode } from 'react'

export function Button({ variant = 'primary', className = '', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'danger' | 'ghost' }) {
  const styles = { primary: 'border-[#6d4aff] bg-gradient-to-r from-[#7252ff] to-[#5a43e8] text-white shadow-[0_5px_14px_rgba(109,74,255,.2)] hover:-translate-y-px hover:shadow-[0_8px_20px_rgba(109,74,255,.25)]', secondary: 'bg-white text-[#4c465d] border-[#e2deea] hover:border-[#cbc3df] hover:bg-[#faf9fd]', danger: 'bg-white text-red-600 border-red-200 hover:bg-red-50', ghost: 'border-transparent bg-transparent text-[#6d667b] hover:bg-[#f0edff] hover:text-[#6042e8]' }
  return <button className={`inline-flex h-9 items-center justify-center gap-2 rounded-[10px] border px-3.5 text-[12px] font-bold disabled:cursor-not-allowed disabled:opacity-55 ${styles[variant]} ${className}`} {...props} />
}
export function Card({ children, className = '' }: PropsWithChildren<{ className?: string }>) { return <section className={`app-card ${className}`}>{children}</section> }
export function Badge({ children, tone = 'neutral' }: PropsWithChildren<{ tone?: 'neutral' | 'blue' | 'green' | 'amber' | 'red' | 'violet' }>) { const tones = { neutral: 'bg-[#f1eff4] text-[#686174]', blue: 'bg-[#edf3ff] text-[#3f63b8]', green: 'bg-emerald-50 text-emerald-700', amber: 'bg-amber-50 text-amber-700', red: 'bg-red-50 text-red-700', violet: 'bg-[#f0edff] text-[#6042e8]' }; return <span className={`inline-flex items-center rounded-full px-2.5 py-1 text-[9px] font-extrabold uppercase tracking-[0.05em] ${tones[tone]}`}>{children}</span> }
export function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description: string; action?: ReactNode }) { return <header className="mb-7 flex flex-wrap items-start justify-between gap-5"><div>{eyebrow && <p className="mb-1.5 text-[10px] font-extrabold uppercase tracking-[0.16em] text-[#6d4aff]">{eyebrow}</p>}<h1 className="text-[25px] font-extrabold tracking-[-0.035em] text-[#19162c] sm:text-[29px]">{title}</h1><p className="mt-2 text-[13px] leading-5 text-[#797286]">{description}</p></div>{action}</header> }
export function Skeleton({ className = '' }: { className?: string }) { return <div aria-hidden="true" className={`skeleton rounded-lg ${className}`} /> }
export function EmptyState({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <div className="rounded-2xl border border-dashed border-[#dcd6e8] bg-[#faf9fd] px-6 py-10 text-center"><span className="mx-auto mb-3 grid size-9 place-items-center rounded-full bg-[#f0edff] text-[#6d4aff]">✦</span><p className="text-sm font-bold text-[#2b2638]">{title}</p><p className="mx-auto mt-1.5 max-w-sm text-xs leading-5 text-[#7b7488]">{description}</p>{action && <div className="mt-4">{action}</div>}</div> }
export function ErrorState({ message, retry }: { message: string; retry?: () => void }) { return <div role="alert" className="rounded-xl border border-red-100 bg-red-50 px-5 py-4"><p className="text-sm font-semibold text-red-800">{message}</p>{retry && <button className="mt-2 text-xs font-bold text-red-700 underline" onClick={retry} type="button">Try again</button>}</div> }
