import type { ButtonHTMLAttributes, PropsWithChildren, ReactNode } from 'react'

export function Button({ variant = 'primary', className = '', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'danger' | 'ghost' }) {
  const styles = { primary: 'bg-[#4f5ff7] text-white border-[#4f5ff7] hover:bg-[#3f4de0] shadow-sm', secondary: 'bg-white text-slate-700 border-slate-200 hover:bg-slate-50', danger: 'bg-white text-red-600 border-red-200 hover:bg-red-50', ghost: 'border-transparent bg-transparent text-slate-600 hover:bg-slate-100' }
  return <button className={`inline-flex h-9 items-center justify-center gap-2 rounded-lg border px-3.5 text-[13px] font-semibold disabled:cursor-not-allowed disabled:opacity-55 ${styles[variant]} ${className}`} {...props} />
}
export function Card({ children, className = '' }: PropsWithChildren<{ className?: string }>) { return <section className={`app-card ${className}`}>{children}</section> }
export function Badge({ children, tone = 'neutral' }: PropsWithChildren<{ tone?: 'neutral' | 'blue' | 'green' | 'amber' | 'red' | 'violet' }>) { const tones = { neutral: 'bg-slate-100 text-slate-600', blue: 'bg-blue-50 text-blue-700', green: 'bg-emerald-50 text-emerald-700', amber: 'bg-amber-50 text-amber-700', red: 'bg-red-50 text-red-700', violet: 'bg-violet-50 text-violet-700' }; return <span className={`inline-flex items-center rounded-full px-2 py-1 text-[10px] font-bold tracking-wide ${tones[tone]}`}>{children}</span> }
export function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description: string; action?: ReactNode }) { return <header className="mb-6 flex flex-wrap items-start justify-between gap-4"><div>{eyebrow && <p className="mb-1 text-[11px] font-bold uppercase tracking-[0.12em] text-[#4f5ff7]">{eyebrow}</p>}<h1 className="text-[24px] font-bold tracking-[-0.025em] text-[#172033] sm:text-[27px]">{title}</h1><p className="mt-1.5 text-[13px] text-[#718096]">{description}</p></div>{action}</header> }
export function Skeleton({ className = '' }: { className?: string }) { return <div aria-hidden="true" className={`skeleton rounded-lg ${className}`} /> }
export function EmptyState({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <div className="rounded-xl border border-dashed border-slate-200 bg-slate-50/60 px-6 py-10 text-center"><p className="text-sm font-bold text-slate-800">{title}</p><p className="mx-auto mt-1.5 max-w-sm text-xs leading-5 text-slate-500">{description}</p>{action && <div className="mt-4">{action}</div>}</div> }
export function ErrorState({ message, retry }: { message: string; retry?: () => void }) { return <div role="alert" className="rounded-xl border border-red-100 bg-red-50 px-5 py-4"><p className="text-sm font-semibold text-red-800">{message}</p>{retry && <button className="mt-2 text-xs font-bold text-red-700 underline" onClick={retry} type="button">Try again</button>}</div> }
