import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link } from 'react-router-dom'

import { Icon } from '../../../components/ui/Icon'
import { Badge, Button, Card, EmptyState, ErrorState, PageHeader, Skeleton } from '../../../components/ui/Primitives'
import { campaignKeys, createCampaign, deleteCampaign, listCampaigns, type CampaignInput, type CampaignStatus } from '../api'
import { CampaignForm } from '../components/CampaignForm'

const tones: Record<CampaignStatus, 'neutral' | 'blue' | 'green' | 'amber' | 'red'> = { DRAFT: 'neutral', ACTIVE: 'green', PAUSED: 'amber', COMPLETED: 'blue', CANCELLED: 'red' }

export function CampaignsPage() {
  const [showForm, setShowForm] = useState(false); const queryClient = useQueryClient()
  const campaigns = useQuery({ queryKey: campaignKeys.all, queryFn: () => listCampaigns() })
  const create = useMutation({ mutationFn: createCampaign, onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: campaignKeys.all }); setShowForm(false) } })
  const remove = useMutation({ mutationFn: deleteCampaign, onSuccess: () => queryClient.invalidateQueries({ queryKey: campaignKeys.all }) })
  return <div className="mx-auto max-w-[1120px]"><PageHeader description="Manage content campaigns and keep related posts together." title="Campaigns" action={<Button onClick={() => setShowForm((value) => !value)}><Icon className="size-4" name={showForm ? 'close' : 'plus'}/>{showForm ? 'Close' : 'Create campaign'}</Button>}/>{showForm && <Card className="mb-5 p-5 sm:p-6"><div className="mb-5"><h2 className="text-[15px] font-bold">Create a campaign</h2><p className="mt-1 text-[11px] text-slate-500">New campaigns use manual approval unless you explicitly change it.</p></div><CampaignForm isSaving={create.isPending} onSubmit={(input: CampaignInput) => create.mutate(input)} submitLabel="Create campaign"/></Card>}{campaigns.isLoading ? <div className="space-y-4">{Array.from({ length: 3 }, (_, index) => <Skeleton className="h-36" key={index}/>)}</div> : campaigns.isError ? <ErrorState message="Unable to load your campaigns." retry={() => void campaigns.refetch()}/> : !campaigns.data?.items.length ? <Card className="p-5"><EmptyState action={<Button onClick={() => setShowForm(true)}>Create campaign</Button>} description="Campaigns help organize related posts around one topic or goal." title="No campaigns yet"/></Card> : <div className="space-y-4">{campaigns.data.items.map((campaign) => <Card className="p-4 sm:p-5" key={campaign.id}><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><div className="grid size-14 shrink-0 place-items-center rounded-xl bg-gradient-to-br from-[#eef1ff] to-[#e5e9ff] text-[#4f5ff7]"><Icon name="campaigns"/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="truncate text-[14px] font-bold">{campaign.name}</h2><Badge tone={tones[campaign.status]}>{campaign.status}</Badge></div><p className="mt-1 text-[11px] text-[#4f5ff7]">{campaign.topic}</p><p className="mt-2 line-clamp-1 text-[11px] text-slate-500">{campaign.description || 'No description provided.'}</p><div className="mt-3 flex flex-wrap gap-x-5 gap-y-1 text-[10px] text-slate-400"><span><b className="text-slate-600">{campaign.post_count}</b> posts</span><span>{campaign.approval_mode.toLowerCase()} approval</span><span>{campaign.duration_days ? `${campaign.duration_days} days` : 'No duration'}</span><span>Created {formatDate(campaign.created_at)}</span></div></div><div className="flex shrink-0 gap-2"><Link className="inline-flex h-9 items-center rounded-lg border border-slate-200 px-3.5 text-[11px] font-bold text-slate-700 hover:bg-slate-50" to={`/campaigns/${campaign.id}`}>Manage</Link>{campaign.status === 'DRAFT' && <Button aria-label={`Delete ${campaign.name}`} disabled={remove.isPending} onClick={() => window.confirm('Delete this campaign? Posts will be kept.') && remove.mutate(campaign.id)} variant="danger"><Icon className="size-4" name="trash"/></Button>}</div></div></Card>)}</div>}</div>
}
function formatDate(value: string) { return new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(value)) }
