import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link } from 'react-router-dom'

import { Button, Card, EmptyState, ErrorState, PageHeader, Skeleton } from '../../../components/ui/Primitives'
import { disconnectLinkedIn, getLinkedInConnectUrl, getLinkedInStatus, linkedinKeys, publishLinkedInTestPost } from '../api'

export function LinkedInSettingsPage() {
  const [commentary, setCommentary] = useState(''); const queryClient = useQueryClient()
  const status = useQuery({ queryKey: linkedinKeys.status, queryFn: getLinkedInStatus })
  const connect = useMutation({ mutationFn: getLinkedInConnectUrl, onSuccess: ({ authorization_url }) => window.location.assign(authorization_url) })
  const disconnect = useMutation({ mutationFn: disconnectLinkedIn, onSuccess: () => queryClient.invalidateQueries({ queryKey: linkedinKeys.status }) })
  const publish = useMutation({ mutationFn: ({ id, text }: { id: string; text: string }) => publishLinkedInTestPost(id, text, crypto.randomUUID()) })
  const account = status.data?.accounts.find((item) => item.is_connected)
  return <div className="mx-auto max-w-[900px]"><Link className="mb-4 inline-block text-xs font-bold text-[#4f5ff7]" to="/settings">← Settings</Link><PageHeader description="Connect the account used for real LinkedIn publishing." title="LinkedIn connection"/>{status.isLoading ? <Skeleton className="h-52"/> : status.isError ? <ErrorState message="Unable to load LinkedIn connection status." retry={() => void status.refetch()}/> : !account ? <Card className="p-6"><EmptyState action={<Button disabled={connect.isPending} onClick={() => connect.mutate()}>{connect.isPending ? 'Preparing…' : 'Connect LinkedIn'}</Button>} description="Authorize access through LinkedIn OAuth. The application never asks for your LinkedIn password." title="No LinkedIn account connected"/></Card> : <div className="space-y-5"><Card className="p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3">{account.profile_image_url ? <img alt="" className="size-11 rounded-full object-cover" src={account.profile_image_url}/> : <span className="grid size-11 place-items-center rounded-full bg-[#eef1ff] font-bold text-[#4f5ff7]">in</span>}<div><div className="flex items-center gap-2"><h2 className="text-sm font-bold">{account.display_name ?? 'LinkedIn member'}</h2><span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-700">Connected</span></div><p className="mt-1 text-xs text-slate-500">Scopes: {account.scopes.split(' ').join(', ')}</p></div></div><Button variant="danger" disabled={disconnect.isPending} onClick={() => window.confirm('Disconnect this LinkedIn account?') && disconnect.mutate(account.id)}>Disconnect</Button></div></Card><Card className="p-5"><h2 className="text-sm font-bold">Publish a test post</h2><p className="mt-1 text-xs leading-5 text-slate-500">This action publishes real content immediately. Review the text carefully before confirming.</p><textarea className="app-input mt-4 min-h-32 resize-y" maxLength={3000} onChange={(event) => setCommentary(event.target.value)} placeholder="Write the exact post to publish…" value={commentary}/>{publish.isError && <p className="mt-3 text-xs font-semibold text-red-600">The test post could not be published.</p>}{publish.isSuccess && <p className="mt-3 text-xs font-semibold text-emerald-600">Test post published successfully.</p>}<div className="mt-4 flex justify-end"><Button disabled={!commentary.trim() || publish.isPending} onClick={() => window.confirm('Publish this text to LinkedIn now?') && publish.mutate({ id: account.id, text: commentary.trim() })}>{publish.isPending ? 'Publishing…' : 'Publish test post'}</Button></div></Card></div>}</div>
}
