import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link } from 'react-router-dom'

import { Badge, Button, Card, EmptyState, PageHeader, Skeleton } from '../../../components/ui/Primitives'
import { ApiError } from '../../../services/api/client'
import { listPosts } from '../../posts/api'
import { analyticsKeys, getAnalyticsOverview, getAnalyticsStatus, getPerformanceInsights, getSchedulingSuggestions, refreshPostAnalytics } from '../api'

export function AnalyticsPage() {
  const client = useQueryClient()
  const status = useQuery({ queryKey: analyticsKeys.status, queryFn: getAnalyticsStatus })
  const overview = useQuery({ queryKey: analyticsKeys.overview, queryFn: getAnalyticsOverview })
  const insights = useQuery({ queryKey: analyticsKeys.insights, queryFn: getPerformanceInsights })
  const scheduling = useQuery({ queryKey: analyticsKeys.scheduling, queryFn: getSchedulingSuggestions })
  const published = useQuery({ queryKey: ['posts', 'analytics-options'], queryFn: () => listPosts({ status: 'PUBLISHED', limit: 100 }) })
  const refresh = useMutation({ mutationFn: refreshPostAnalytics, onSuccess: async () => { await Promise.all([client.invalidateQueries({ queryKey: analyticsKeys.overview }), client.invalidateQueries({ queryKey: analyticsKeys.insights })]) } })
  const error = refresh.error instanceof ApiError ? refresh.error.message : refresh.isError ? 'Analytics could not be refreshed.' : null
  const captured = new Set(overview.data?.posts.map((item) => item.post_id) ?? [])
  return <div className="mx-auto max-w-[1120px]">
    <PageHeader title="Analytics" description="Performance metrics collected from your own published LinkedIn posts."/>
    {status.isLoading ? <Skeleton className="mb-5 h-20"/> : !status.data?.collection_available && <Card className="mb-5 border-amber-200 bg-amber-50 p-4"><p className="text-[12px] font-bold text-amber-900">{status.data?.connected ? 'Analytics permission required' : 'Connect LinkedIn to collect analytics'}</p><p className="mt-1 text-[11px] leading-5 text-amber-700">{status.data?.connected ? <>Your token does not include <code>{status.data.required_scope}</code>. Community Management API approval and reconnection are required.</> : 'Analytics are never estimated or filled with sample data.'}</p><Link className="mt-3 inline-block text-[11px] font-bold text-amber-800 underline" to="/settings/linkedin">Manage LinkedIn</Link></Card>}
    {error && <p className="mb-4 rounded-lg bg-red-50 px-3 py-2 text-[11px] text-red-700" role="alert">{error}</p>}
    <div className="mb-5 grid grid-cols-2 gap-3 lg:grid-cols-5"><Metric label="Impressions" value={format(overview.data?.total_impressions)}/><Metric label="Reactions" value={format(overview.data?.total_likes)}/><Metric label="Comments" value={format(overview.data?.total_comments)}/><Metric label="Reshares" value={format(overview.data?.total_shares)}/><Metric label="Avg. engagement" value={overview.data?.average_engagement_rate == null ? 'Unavailable' : `${overview.data.average_engagement_rate.toFixed(2)}%`}/></div>
    {overview.data?.posts.length ? <Card className="mb-5 p-5"><h2 className="text-[14px] font-bold">Impressions by post</h2><p className="mt-1 text-[11px] text-slate-500">Latest real LinkedIn snapshot for each measured post.</p><div className="mt-5 space-y-3">{overview.data.posts.slice(0, 8).map((item) => { const maximum = Math.max(...overview.data.posts.map((post) => post.analytics.impressions ?? 0), 1); const value = item.analytics.impressions; return <div className="grid grid-cols-[140px_1fr_60px] items-center gap-3" key={item.post_id}><span className="truncate text-[11px] font-semibold text-slate-600">{item.title || item.content_excerpt}</span><div className="h-2.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-indigo-500 to-violet-500" style={{ width: value == null ? '0%' : `${Math.max((value / maximum) * 100, 2)}%` }}/></div><span className="text-right text-[10px] font-bold text-slate-500">{format(value)}</span></div>})}</div></Card> : null}
    <Card className="mb-5 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-[14px] font-bold">Performance insights</h2><p className="mt-1 text-[11px] text-slate-500">Patterns observed only in your measured post history.</p></div><Badge tone="blue">Your data</Badge></div>{insights.isLoading ? <Skeleton className="mt-4 h-32"/> : insights.data?.status === 'insufficient_data' ? <div className="mt-4 rounded-lg bg-slate-50 p-4"><p className="text-[12px] font-bold">More data is needed</p><p className="mt-1 text-[11px] leading-5 text-slate-500">Insights require at least {insights.data.minimum_required} posts with engagement data. Currently available: {insights.data.analyzed_posts}.</p></div> : <div className="mt-4 grid gap-3 md:grid-cols-2">{insights.data?.insights.map((item) => <div className="rounded-lg border border-slate-100 p-4" key={item.type}><p className="text-[11px] font-bold text-[#4f5ff7]">{item.title}</p><p className="mt-2 text-[12px] font-semibold leading-5 text-slate-700">{item.observation}</p><p className="mt-2 text-[10px] leading-4 text-slate-400">{item.evidence}</p></div>)}</div>}<p className="mt-4 text-[10px] leading-4 text-slate-400">{insights.data?.disclaimer}</p></Card>
    <Card className="mb-5 p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="text-[14px] font-bold">Suggested posting windows</h2><p className="mt-1 text-[11px] text-slate-500">Personalized from repeated windows in your own measured history.</p></div><Badge tone="violet">Historical data</Badge></div>{scheduling.isLoading ? <Skeleton className="mt-4 h-28"/> : scheduling.data?.status !== 'ready' ? <div className="mt-4 rounded-lg bg-slate-50 p-4 text-[11px] leading-5 text-slate-500">Not enough repeated historical data yet. Personalized windows appear after at least {scheduling.data?.minimum_required ?? 5} measured posts.</div> : <div className="mt-4 grid gap-3 sm:grid-cols-3">{scheduling.data.suggestions.map((item) => <div className="rounded-xl border border-indigo-100 bg-indigo-50/50 p-4" key={`${item.weekday}-${item.time}`}><p className="text-xs font-bold text-indigo-900">{item.weekday}</p><p className="mt-1 text-xl font-bold text-indigo-600">{item.time}</p><p className="text-[10px] text-indigo-400">{item.timezone}</p><p className="mt-3 text-[10px] leading-4 text-slate-500">{item.evidence}</p></div>)}</div>}<p className="mt-4 text-[10px] leading-4 text-slate-400">{scheduling.data?.disclaimer}</p></Card>
    {published.data?.items.some((post) => !captured.has(post.id)) && <Card className="mb-5 p-5"><h2 className="text-[14px] font-bold">Published posts awaiting metrics</h2><div className="mt-3 flex flex-wrap gap-2">{published.data.items.filter((post) => !captured.has(post.id)).map((post) => <Button disabled={!status.data?.collection_available || refresh.isPending} key={post.id} onClick={() => refresh.mutate(post.id)} variant="secondary">Collect: {post.title || post.content.slice(0, 30)}</Button>)}</div></Card>}
    <Card className="p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-[14px] font-bold">Post performance</h2><p className="mt-1 text-[11px] text-slate-500">Latest lifetime snapshot returned by LinkedIn.</p></div><Badge tone="blue">Own data</Badge></div>{overview.isLoading ? <Skeleton className="h-64"/> : overview.data?.posts.length ? <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="border-b border-slate-100 text-[9px] uppercase tracking-wide text-slate-400"><th className="py-3">Post</th><th>Impressions</th><th>Reactions</th><th>Comments</th><th>Reshares</th><th>Engagement</th><th>Captured</th><th/></tr></thead><tbody>{overview.data.posts.map((item) => <tr className="border-b border-slate-50 text-[11px]" key={item.post_id}><td className="max-w-64 py-3 pr-4"><Link className="block truncate font-bold hover:text-[#4f5ff7]" to={`/posts/${item.post_id}`}>{item.title || item.content_excerpt}</Link></td><td>{format(item.analytics.impressions)}</td><td>{format(item.analytics.likes)}</td><td>{format(item.analytics.comments)}</td><td>{format(item.analytics.shares)}</td><td>{item.analytics.engagement_rate == null ? '—' : `${item.analytics.engagement_rate.toFixed(2)}%`}</td><td>{new Date(item.analytics.captured_at).toLocaleDateString()}</td><td><Button disabled={!status.data?.collection_available || refresh.isPending} onClick={() => refresh.mutate(item.post_id)} variant="ghost">Refresh</Button></td></tr>)}</tbody></table></div> : <EmptyState title="No analytics collected" description="Metrics appear only after LinkedIn returns data for a published post."/>}</Card>
  </div>
}

function Metric({ label, value }: { label: string; value: string }) { return <Card className="p-4"><p className="text-[9px] font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-2 text-[18px] font-bold">{value}</p></Card> }
function format(value: number | null | undefined) { return value == null ? 'Unavailable' : new Intl.NumberFormat().format(value) }
